### ISSUE TITLE
Docker hub

### ISSUE THREAD

**Issue by capps1994** [waneal/ecs-daemon-protector#1]
Is there any way we can get this into the docker hub? As we have many accounts to that need this workaround

**Comment by capps1994** [comment]
Sorry to pester, but if you are happy to set up an image in docker hub could you please update this issue, it would be greatly appreciated. I am happy to test this further if it gets on docker hub with our set up, will let you know of any issues.

**Comment by waneal** [comment]
@capps1994 Thank you for your comment. I created the repository, and I hope this image could help you.

https://hub.docker.com/r/iamwaneal/ecs-daemon-protector

**Comment by capps1994** [comment]
thank you very much I'll will pull and test
